@hostname = http://localhost:5059
### get /todos
GET {{hostname}}/todos
### get /todos/{id}
GET {{hostname}}/todos/9
### post /todos
POST {{hostname}}/todos
Content-Type: application/json

{
    "title": "Study mah dude",
    "description": "fake description",
    "completed": false
}
### put /todos/{id}
PUT {{hostname}}/todos/16
Content-Type: application/json

{
    "title": "Done Groceries =D",
    "description": "bought everything =).",
    "completed": true
}
### delete /todos/{id}
DELETE {{hostname}}/todos/16
### post /register
POST {{hostname}}/register
Content-Type: application/json

{
    "username": "chucktesta",
    "password": "123456"
}
### post /login
POST {{hostname}}/login
Content-Type: application/json

{
    "username": "chucktesta",
    "password": "123456"
}