@hostname = http://localhost:5059
### get /todos
GET {{hostname}}/todos
### get /todos/{id}
GET {{hostname}}/todos/5
### post /todos
POST {{hostname}}/todos
Content-Type: application/json

{
    "title": "Study mah dude",
    "description": "fake description",
    "completed": false
}
### put /todos/{id}
PUT {{hostname}}/todos/2
Content-Type: application/json

{
    "title": "Done Groceries =D",
    "description": "bought everything =).",
    "completed": true
}
### delete /todos/{id}
DELETE {{hostname}}/todos/1
